# Generated by Django 2.2.1 on 2019-08-29 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0002_auto_20190829_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='prediction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nfl.Team'),
        ),
    ]
