# Generated by Django 2.2.1 on 2019-09-01 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0003_auto_20190829_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='year',
        ),
        migrations.AddField(
            model_name='game',
            name='gametime',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 1, 15, 2, 46, 121476)),
        ),
    ]
