# Generated by Django 2.2.1 on 2019-09-02 03:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0005_auto_20190901_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gametime',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 1, 23, 34, 22, 800448)),
        ),
    ]
