# Generated by Django 2.2.1 on 2019-09-02 23:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0011_auto_20190902_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gametime',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 2, 19, 49, 44, 57696)),
        ),
    ]
