# Generated by Django 2.2.1 on 2019-09-03 00:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0017_auto_20190903_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gametime',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 2, 20, 17, 48, 654203)),
        ),
    ]
