# Generated by Django 2.2.1 on 2019-09-03 00:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0018_auto_20190903_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gametime',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 2, 20, 42, 39, 78049)),
        ),
    ]
