# Generated by Django 2.2.1 on 2019-09-03 00:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0020_auto_20190903_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gametime',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 2, 20, 45, 37, 212130)),
        ),
    ]
