# Generated by Django 2.2.1 on 2019-09-05 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0029_auto_20190905_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gametime',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 5, 18, 42, 18, 848285)),
        ),
    ]
