# Generated by Django 2.2.1 on 2019-09-05 23:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0033_auto_20190905_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gametime',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 5, 19, 4, 25, 149002)),
        ),
    ]
