# Generated by Django 2.2.1 on 2019-09-07 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0070_auto_20190907_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gametime',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 7, 14, 45, 12, 578858)),
        ),
    ]
