# Generated by Django 2.2.1 on 2019-09-08 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0072_auto_20190907_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gametime',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 8, 12, 14, 57, 853308)),
        ),
    ]
