# Generated by Django 2.2.1 on 2019-09-09 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0074_auto_20190909_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gametime',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 9, 18, 17, 13, 793962)),
        ),
    ]
