# Generated by Django 2.2.1 on 2019-09-09 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0076_auto_20190909_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='prediction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nfl.Team'),
        ),
    ]
