# Generated by Django 2.2.1 on 2019-09-09 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0078_auto_20190909_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfl.Game'),
        ),
    ]
