# Generated by Django 2.2.1 on 2019-09-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0079_auto_20190909_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='gb',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
