# Generated by Django 2.2.1 on 2019-09-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0080_player_gb'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='abbrv',
            field=models.TextField(default=''),
        ),
    ]
