# Generated by Django 2.2.1 on 2019-09-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0081_team_abbrv'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='success',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
