# Generated by Django 2.2.1 on 2019-10-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0082_selection_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='cell',
            field=models.TextField(default='+18142031414'),
        ),
    ]
