# Generated by Django 2.2.1 on 2019-10-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0083_player_cell'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='flosses',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='fties',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='fwins',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
