# Generated by Django 2.2.1 on 2019-10-04 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0084_auto_20191003_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=2019)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfl.Player')),
            ],
        ),
    ]
